"""initial_schema

Revision ID: 217dbdf39456
Revises: 
Create Date: 2026-02-25 00:27:00.109933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217dbdf39456'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('biometric_readings',
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('sleep_duration', sa.Float(), nullable=False),
    sa.Column('sleep_efficiency', sa.Float(), nullable=False),
    sa.Column('deep_sleep_pct', sa.Float(), nullable=False),
    sa.Column('rem_sleep_pct', sa.Float(), nullable=False),
    sa.Column('hrv_rmssd', sa.Float(), nullable=False),
    sa.Column('resting_hr', sa.Float(), nullable=False),
    sa.Column('temperature_deviation', sa.Float(), nullable=False),
    sa.Column('activity_score', sa.Integer(), nullable=False),
    sa.Column('activity_calories', sa.Integer(), nullable=False),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('deep_sleep_pct >= 0 AND deep_sleep_pct <= 100', name='ck_deep_sleep_pct'),
    sa.CheckConstraint('rem_sleep_pct >= 0 AND rem_sleep_pct <= 100', name='ck_rem_sleep_pct'),
    sa.CheckConstraint('sleep_efficiency >= 0 AND sleep_efficiency <= 100', name='ck_sleep_efficiency'),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('contextual_data',
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('barometric_pressure', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('menstrual_phase', sa.Text(), nullable=True),
    sa.Column('stress_event', sa.Text(), nullable=True),
    sa.Column('medication_change', sa.Text(), nullable=True),
    sa.Column('exercise_type', sa.Text(), nullable=True),
    sa.Column('exercise_rpe', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("menstrual_phase IS NULL OR menstrual_phase IN ('menstrual', 'follicular', 'ovulatory', 'luteal', 'not_applicable')", name='ck_menstrual_phase'),
    sa.CheckConstraint('exercise_rpe IS NULL OR (exercise_rpe >= 1 AND exercise_rpe <= 10)', name='ck_exercise_rpe'),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('correlation_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('computed_at', sa.Text(), nullable=False),
    sa.Column('metric_a', sa.Text(), nullable=False),
    sa.Column('metric_b', sa.Text(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('correlation_coefficient', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('date_range_start', sa.Text(), nullable=False),
    sa.Column('date_range_end', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlation_cache', schema=None) as batch_op:
        batch_op.create_index('idx_correlation_cache_computed', ['computed_at'], unique=False)
        batch_op.create_index('idx_correlation_cache_metrics', ['metric_a', 'metric_b', 'lag_days'], unique=False)

    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('pain_severity', sa.Integer(), nullable=False),
    sa.Column('pain_locations', sa.Text(), nullable=False),
    sa.Column('fatigue_severity', sa.Integer(), nullable=False),
    sa.Column('brain_fog', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('is_flare', sa.Boolean(), nullable=False),
    sa.Column('flare_severity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint('brain_fog >= 0 AND brain_fog <= 10', name='ck_brain_fog'),
    sa.CheckConstraint('fatigue_severity >= 0 AND fatigue_severity <= 10', name='ck_fatigue_severity'),
    sa.CheckConstraint('flare_severity IS NULL OR (flare_severity >= 1 AND flare_severity <= 10)', name='ck_flare_severity'),
    sa.CheckConstraint('mood >= 0 AND mood <= 10', name='ck_mood'),
    sa.CheckConstraint('pain_severity >= 0 AND pain_severity <= 10', name='ck_pain_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.create_index('idx_symptom_logs_date', ['date'], unique=False)
        batch_op.create_index('idx_symptom_logs_is_flare', ['is_flare'], unique=False, sqlite_where=sa.text('is_flare = 1'))

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('sync_type', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index('idx_sync_log_source', ['source', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index('idx_sync_log_source')

    op.drop_table('sync_log')
    with op.batch_alter_table('symptom_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_symptom_logs_is_flare', sqlite_where=sa.text('is_flare = 1'))
        batch_op.drop_index('idx_symptom_logs_date')

    op.drop_table('symptom_logs')
    with op.batch_alter_table('correlation_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_correlation_cache_metrics')
        batch_op.drop_index('idx_correlation_cache_computed')

    op.drop_table('correlation_cache')
    op.drop_table('contextual_data')
    op.drop_table('biometric_readings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
